[package]
name = "lista1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "7.0.1"
unicode-segmentation = "1.10.1"
